"""empty message

Revision ID: ae6d495a83ab
Revises: 
Create Date: 2024-09-30 08:46:50.310694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6d495a83ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('nivel_tostado', sa.Integer(), nullable=False),
    sa.Column('perfil_sabor', sa.JSON(), nullable=False),
    sa.Column('opcion_molido', sa.JSON(), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('producto_id')
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('codigo_postal', sa.String(length=120), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carritos',
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('carrito_id')
    )
    op.create_table('carrito_producto',
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.carrito_id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.PrimaryKeyConstraint('carrito_id', 'producto_id')
    )
    op.create_table('pedidos',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=False),
    sa.Column('total_facturacion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.carrito_id'], ),
    sa.PrimaryKeyConstraint('pedido_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('carrito_producto')
    op.drop_table('carritos')
    op.drop_table('usuarios')
    op.drop_table('productos')
    # ### end Alembic commands ###
